Repository tihanyibalazsmate/Rajongoi9A-A, pull requests merged in 2024-03, with the labels that each got.

#16 media oldal modositasai
  media.html
Labels: fejlesztés, Lackó

#17 fooldal modositasa
  fooldal.html
Labels: fejlesztés, Gergely

#21 card szin es css
  rolunk.html
  styles.css
Labels: Balázs

#22 carousel
  media.html
Labels: Lackó

#23 szöveg formázása
  fooldal.html
Labels: Gergely

#27 kepek és szinek
  kepek/gergely.jpg
  kepek/lacko.jpg
  rolunk.html
  styles.css
Labels: dokumentáció, Balázs

#28 carousel athelyezese es atnevezes + css
  index.html
  media.html
  quiz.html
  rolunk.html
  styles.css
Labels: fejlesztés, Lackó

#31 javitasok
  rolunk.html
  styles.css
Labels: dokumentáció, Lackó

#33 telefonos nézet
  media.html
  quiz.html
  rolunk.html
Labels: dokumentáció, Balázs

#35 arnyek es css
  index.html
  styles.css
Labels: Gergely, html

#37 javitasok
  index.html
  styles.css
Labels: Balázs

#39 valtoztatasok
  index.html
  rolunk.html
  styles.css
Labels: dokumentáció, Gergely

#44 kepek css rolunk valtoztatasa
  kepek/balazsuj.jpg
  kepek/hatter.jpg
  kepek/hatterszurke.jpg
  rolunk.html
  styles.css
Labels: dokumentáció, Balázs

#43 szöveg közepre igazitasa
  index.html
Labels: dokumentáció, Gergely

#45 quiz oldal fejlesztesenek elkezdese
  quiz.html
Labels: fejlesztés, Lackó

#50 szöveg divekre osztasa es css
  index.html
  styles.css
Labels: Gergely

#49 quiz oldal fejlesztése
  questions.js
  quiz.html
  script.js
  styles.css
Labels: fejlesztés, Lackó

#51 rolunk es css valtoztatasa
  rolunk.html
  styles.css
Labels: Balázs

#53 hibak javitasa
  index.html
  rolunk.html
  styles.css
Labels: hiba, Balázs

#55 apro javitasok es navbar fix
  index.html
  media.html
  navbar.js
  quiz.html
  rolunk.html
  styles.css
Labels: Balázs

#60 quiz oldal popupinfo elkezdese
  quiz.html
  script.js
  styles.css
Labels: fejlesztés, Lackó

#61 media oldal, rolunk oldal es css valtoztasa
  media.html
  rolunk.html
  styles.css
Labels: dokumentáció, Gergely

#63 kisebb javitasok
  index.html
  rolunk.html
  styles.css
Labels: dokumentáció, Balázs

#64 hatter-elmosas
  quiz.html
  script.js
  styles.css
Labels: fejlesztés, Lackó

#65 kerdesek hozzaadasa es oldal lapozasa
  questions.js
  quiz.html
  quiz.txt
  script.js
  styles.css
Labels: fejlesztés, Lackó

#67 66 navbar es footer animacio
  index.html
  media.html
  navbar.js
  quiz.html
  rolunk.html
  styles.css
Labels: Balázs

#69 quiz oldal folytatása és javitások
  media.html
  quiz.html
  script.js
  styles.css
Labels: dokumentáció, Balázs, pr
