Repository tihanyibalazsmate/Rajongoi9A-A, pull requests merged in 2024-04, with the labels that each got.

#71 quiz oldal befejezve
  index.html
  media.html
  questions.js
  quiz.html
  script.js
  styles.css
Labels: dokumentáció, fejlesztés, Lackó

#72 javitasok es utolso simitasok
  index.html
  quiz.html
  rolunk.html
  styles.css
Labels: Balázs

#74 fixalasok
  index.html
  media.html
  quiz.html
  rolunk.html
  styles.css
Labels: Balázs

#76 proba
  quiz.html
  styles.css
Labels: bajos, Balázs

#78 szoveg kiegeszitese
  index.html
Labels: dokumentáció, Gergely
